#!/usr/bin/env node
'use strict'

const { join } = require('path')
const { readFileSync, writeFileSync } = require('fs')

function createWebview(appName) {
  const webRoot = join(__dirname, '..', 'web')
  const webAppRoot = join(webRoot, appName)
  const indexPath = join(webAppRoot, 'index.html')
  const indexHtml = readFileSync(indexPath, 'utf8')

  const buildJsPath = join(webAppRoot, 'dist', 'build.js')
  const buildJs = readFileSync(buildJsPath, 'utf8')

  const indexHtmlLines = indexHtml.split('\n')
  const mainJsLines = buildJs.split('\n')
  // remove:
  //     <script src="./dist/build.js"></script>
  //   </body>
  // </html>
  const html = indexHtmlLines.slice(0, -4)
    .concat('<script>')
      .concat(mainJsLines)
    .concat('</script')
    .concat([ '</body>', '</html>' ])
    .join('\n')

  const targetPath = join(webAppRoot, 'webview.html')
  writeFileSync(targetPath, html, 'utf8')
}

const appName = process.argv[2]
createWebview(appName)
